   apiVersion: apps/v1
   kind: Deployment
   metadata:
    name: db-noticias-deployment
   spec:
    template:
     metadata:
      name: db-noticias
      labels:
       app: db-noticias
     spec:
      containers:
       - name: portal-noticias-container
         image: aluracursos/mysql-db:1
         ports:
          - containerPort: 3306 #porta do container que sera acessada dentro do cluster
         envFrom:
          - configMapRef:
             name: db-configmap
    replicas: 2
    selector:
     matchLabels:
      app: db-noticias
